source 'https://rubygems.org'
gem 'rspec'
gem 'poltergeist'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'sequel'
gem 'json'
gem 'test-unit'
gem 'pg'
gem 'fileutils'
gem 'rmagick'

group :development do
  gem 'guard'
  gem 'guard-rspec'
end
